madlibsgenerator/madlibsgenerator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path("blankblank", admin.site.urls),
]

madlibsgenerator/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
	path('', views.index, name='index'),
	path('play/<int:madlib_id>/', views.Play.as_view(), name='play'),
	path('generate', views.generate_madlib, name='generate'),
]

madlibsgenerator/main/models.py
from django.db import models

class BaseText(models.Model):
	text = models.CharField(max_length=600)
	creation_date = models.DateTimeField('creation date', auto_now_add=True)
	def __str__(self):
		return self.text[:10]

class Substitution(models.Model):
	base_text = models.ForeignKey(BaseText, on_delete=models.CASCADE)
	swap_id = models.IntegerField()
	pos = models.CharField(max_length=10)
	lemma = models.CharField(max_length=20)
	def __str__(self):
		return f"({self.swap_id}: {self.pos}-{self.lemma})"

madlibsgenerator/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template import loader
from django.views.generic import TemplateView

from .models import BaseText, Substitution

from . import madlibs

import re

def index(request):
	return render(request, 'main/index.html')


def generate_madlib(request):
	text = request.POST['basetext']
	if len(text) > 3000:
		return redirect("/")
	if 'http' in text or '@' in text or re.search(r"[A-Za-z0-9]+\.[a-z0-9]{1,4}\b", text):
		return redirect("/")
	basetext, substitutions = madlibs.generate_madlib(text)
	basetext_obj = BaseText(text=basetext)
	basetext_obj.save()
	for (sub_lemma, sub_pos),sub_swap_id in substitutions.items():
		substitution_obj = basetext_obj.substitution_set.create(swap_id=sub_swap_id, pos=sub_pos, lemma=sub_lemma)
		substitution_obj.save()
	context = {
		'basetext': basetext_obj,
		'substitution_set': basetext_obj.substitution_set.all(),
	}
	return render(request, "main/generation.html", context)


class Play(TemplateView):
	def get(self, request, madlib_id):
		basetext = get_object_or_404(BaseText, pk=madlib_id)
		substitution_set = basetext.substitution_set.all()
		context = {
			'basetext': basetext,
			'substitution_list': substitution_set,
		}
		return render(request, "main/play.html", context)

	def post(self, request, madlib_id):
		basetext = get_object_or_404(BaseText, pk=madlib_id)
		substitutions = {}
		for substitution in basetext.substitution_set.all():
			key = f"swap-{substitution.swap_id}"
			if key not in request.POST:
				return HttpResponse('Missing sub')
			swap_id = key.split('-')[-1]
			substitutions[swap_id] = request.POST[key]
		context = {
			'text': madlibs.sub_inflected(basetext.text, substitutions),
			'basetext': basetext,
		}
		return render(request, "main/filled.html", context)

madlibsgenerator/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Madlib Generator</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'main/favicon.ico' %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body class="bg-light">
	<div class="container">
		<h1 hidden>Madlibs Generator</h1>
		<a href="/">
			<img src="{% static 'main/logo.png' %}" style="max-height:200px;max-width:100%">
		</a>
		<h3>with AI power!</h3>
		<hr>
		{% block content %}
		{% endblock %}
	</div>
<body>

madlibsgenerator/main/templates/main/filled.html
{% extends 'main/base.html' %}

{% block content %}
<h2>Filled Madlib</h2>
<div class="container p-3 border">
	{{ text | linebreaksbr }}
</div>
<div class="text-right mt-3">
	<a href="{% url 'main:play' basetext.id %}" class="btn btn-primary">Play again</a>
	<a href="/" class="btn btn-primary">Create your own!</a>
</div>
{% endblock %}

madlibsgenerator/main/templates/main/generation.html
{% extends 'main/base.html' %}

{% block content %}
<h2>Madlib Generated</h2>
<div class="container p-3 border">
	{{ basetext.text | linebreaksbr }}
</div>
<div class="text-right mt-3">
	<a href="{% url 'main:play' basetext.id %}" class="btn btn-primary">Play</a>
	<button onclick="navigator.clipboard.writeText('{{ request.get_host }}{% url 'main:play' basetext.id %}')" class="btn btn-primary">copy link</button>
</div>
{% endblock %}

madlibsgenerator/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<h2>Enter your text</h2>
<form action="{% url 'main:generate' %}" method="post" class="mt-3">
	{% csrf_token %}
	<div class="form-group">
		<textarea id="basetext" name="basetext" rows="6" cols="100" style="resize: none;" class="form-control"></textarea>
		<span id="length-count">0</span> characters
		<br>
		<input type="submit" value="Generate" class="btn btn-primary">
	</div>
</form>
<script>
	const textarea = document.querySelector("textarea");
	const lengthCount = document.querySelector("#length-count");
	textarea.addEventListener("input", ({ currentTarget: target }) => {
		lengthCount.innerText = target.value.length;
	});
</script>
<br>
<h3>Hints</h3>
<ul>
	<li>It's advised you use more than 50 characters, but fewer than 200 characters for best results.</li>
	<li>Try using the chorus of your favorite song, or a stanza of your favorite poem!</li>
	<li>The less slang and jargon in your input, the better our AI is to understand and process your input.</li>
</ul>
{% endblock %}

madlibsgenerator/main/templates/main/play.html
{% extends 'main/base.html' %}

{% block content %}
<h2>Fill in the Parts of Speech</h2>
Don't worry about conjugation and inflection: our AI will do it for you!
<form action="{% url 'main:play' basetext.id %}" method="post" class="mt-3">
	{% csrf_token %}
	<div class="container py-2 my-1 border">
		{% for substitution in substitution_list %}
			<div class="input-group my-2 flex-nowrap align-items-center">
				<label for="swap-{{ substitution.swap_id }}" class="col-auto me-3 col-form-label">{{ substitution.pos }} : </label>
				<input type="text" id="swap-{{ substitution.swap_id }}" name="swap-{{ substitution.swap_id }}" class="col form-control">
			</div>
		{% endfor %}
	</div>
	<input type="submit" value="Fill" class="btn btn-primary">
</form>
{% endblock %}